/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alimetarpanda;
import alimetarpanda.cdialog;

import java.awt.MouseInfo;
import java.awt.Point;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
/**
 *
 * @author Carmen Jimenez
 */

public class comedor extends javax.swing.JFrame {
    ImageIcon nada;
    ImageIcon pandaInicio =new ImageIcon (getClass().getResource("/alimetarpanda/imagenes/panda_feliz.gif"));  
    ImageIcon pandaBambu = new ImageIcon (getClass().getResource("/alimetarpanda/imagenes/2.png"));
    ImageIcon pandaMolesto=new ImageIcon (getClass().getResource("/alimetarpanda/imagenes/comiendo.png"));  ;
    int x,y;
    int c,si=0,si2=0;
    boolean v= false,p=true;
    /**
     * Creates new form comedor
     */
    public comedor() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cerrar = new javax.swing.JButton();
        c4 = new javax.swing.JLabel();
        c1 = new javax.swing.JLabel();
        c2 = new javax.swing.JLabel();
        c3 = new javax.swing.JLabel();
        c5 = new javax.swing.JLabel();
        c6 = new javax.swing.JLabel();
        c7 = new javax.swing.JLabel();
        c8 = new javax.swing.JLabel();
        c9 = new javax.swing.JLabel();
        panda = new javax.swing.JLabel();
        roca = new javax.swing.JLabel();
        reiniciar = new javax.swing.JButton();
        mas = new javax.swing.JButton();
        fondocomida = new javax.swing.JLabel();
        sanar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alimetarpanda/imagenes/cerrar_icono_pequeño.png"))); // NOI18N
        cerrar.setBorder(null);
        cerrar.setContentAreaFilled(false);
        cerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, -1));

        c4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alimetarpanda/comida/comida_insecto.png"))); // NOI18N
        c4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                c4MouseDragged(evt);
            }
        });
        c4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                c4MousePressed(evt);
            }
        });
        getContentPane().add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 70, 70));

        c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alimetarpanda/comida/botella.png"))); // NOI18N
        c1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                c1MouseDragged(evt);
            }
        });
        c1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                c1MousePressed(evt);
            }
        });
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, 120));

        c2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alimetarpanda/comida/comida_bambu.png"))); // NOI18N
        c2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                c2MouseDragged(evt);
            }
        });
        c2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                c2MousePressed(evt);
            }
        });
        getContentPane().add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 80, 70));

        c3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alimetarpanda/comida/comida_cereza.png"))); // NOI18N
        c3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                c3MouseDragged(evt);
            }
        });
        c3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                c3MousePressed(evt);
            }
        });
        getContentPane().add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 80, 70));

        c5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alimetarpanda/comida/comida_durazno.png"))); // NOI18N
        c5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                c5MouseDragged(evt);
            }
        });
        c5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                c5MousePressed(evt);
            }
        });
        getContentPane().add(c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 60, 60));

        c6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alimetarpanda/comida/comida_insectoM.png"))); // NOI18N
        c6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                c6MouseDragged(evt);
            }
        });
        c6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                c6MousePressed(evt);
            }
        });
        getContentPane().add(c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 50, 70));

        c7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alimetarpanda/comida/comida_pez.png"))); // NOI18N
        c7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                c7MouseDragged(evt);
            }
        });
        c7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                c7MousePressed(evt);
            }
        });
        getContentPane().add(c7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 80, 40));

        c8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alimetarpanda/comida/zapato.gif"))); // NOI18N
        c8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                c8MouseDragged(evt);
            }
        });
        c8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                c8MousePressed(evt);
            }
        });
        getContentPane().add(c8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 50, 50));

        c9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alimetarpanda/comida/comida_pez2.png"))); // NOI18N
        c9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                c9MouseDragged(evt);
            }
        });
        c9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                c9MousePressed(evt);
            }
        });
        getContentPane().add(c9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 80, 40));

        panda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alimetarpanda/imagenes/panda_feliz.gif"))); // NOI18N
        getContentPane().add(panda, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, -1, -1));

        roca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alimetarpanda/imagenes/roca.png"))); // NOI18N
        getContentPane().add(roca, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 290, 130));

        reiniciar.setFont(new java.awt.Font("Shadows Into Light", 1, 18)); // NOI18N
        reiniciar.setForeground(new java.awt.Color(255, 255, 255));
        reiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alimetarpanda/imagenes/volver.png"))); // NOI18N
        reiniciar.setText("Reiniciar");
        reiniciar.setBorderPainted(false);
        reiniciar.setContentAreaFilled(false);
        reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarActionPerformed(evt);
            }
        });
        getContentPane().add(reiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 160, 30));

        mas.setFont(new java.awt.Font("Shadows Into Light", 1, 18)); // NOI18N
        mas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alimetarpanda/imagenes/naranja.jpg"))); // NOI18N
        mas.setText("Agregar mas");
        mas.setBorderPainted(false);
        mas.setContentAreaFilled(false);
        mas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masActionPerformed(evt);
            }
        });
        getContentPane().add(mas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 130, 30));

        fondocomida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alimetarpanda/imagenes/rosa_pequeño.png"))); // NOI18N
        getContentPane().add(fondocomida, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 240, 350));

        sanar.setFont(new java.awt.Font("Shadows Into Light", 1, 18)); // NOI18N
        sanar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alimetarpanda/imagenes/naranja.jpg"))); // NOI18N
        sanar.setText("Sanar");
        sanar.setBorderPainted(false);
        sanar.setContentAreaFilled(false);
        sanar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sanar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sanarActionPerformed(evt);
            }
        });
        getContentPane().add(sanar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 110, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alimetarpanda/imagenes/fondo_bambu.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void eventoMouse(java.awt.event.MouseEvent evt){
        
        x=evt.getX();
        y=evt.getY();
    }
    public void puntoMouse(JLabel label,String img){
        v=true;
        label.setVisible(v);
        
        Point point = MouseInfo.getPointerInfo().getLocation();
        
        System.out.println(point);
        label.setLocation(point.x-370,point.y-160);
        panda.getLocation();
        if((label.getX()>510)&&(label.getY()>300)&&(label.getX()<565)&&(label.getY()<320)){
            label.setVisible(false);
            if(("c1".equals(img))||("c8".equals(img))){
            v=false;
            panda.setIcon(pandaMolesto);
            p=false;
            if(si==0){
             cdialog dialogo=new cdialog("<html>Pandi esta enfermo, !curalo!"); 
             dialogo.setVisible(true);
            // co=new cdialog("<html>Pandi esta enfermo, !curalo!");
            //co.setVisible(true);
            si++;
            }
            else if("c2".equals(img)&&(v==true)&&(p==true)){
            panda.setIcon(pandaBambu);
            if(si2==0){
            cdialog dialog=new cdialog("<html>Pandi AMA le bambú, !Alimentalo mas!");
            dialog.setVisible(true);
            //JOptionPane.showMessageDialog(null,"Pandi AMA le bambú, !Alimentalo mas!");
            si2++;
            }
            }
            else if(((!"c1".equals(img))||(!"c8".equals(img))||(!"c2".equals(img)))&&(v==true)&&(p==true)){
            panda.setIcon(pandaInicio);
        }
        }       
    }
    
    }
    
    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cerrarActionPerformed

    private void reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciarActionPerformed
        // TODO add your handling code here:
        c1.setVisible(true);
        c2.setVisible(true);
        c3.setVisible(true);
        c4.setVisible(true);
        c5.setVisible(true);
        c6.setVisible(true);
        c7.setVisible(true);
        c8.setVisible(true);
        c9.setVisible(true);
        panda.setIcon(pandaInicio);
        v= false;
        p=true;
    }//GEN-LAST:event_reiniciarActionPerformed

    private void c1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c1MousePressed
        this.eventoMouse(evt);
        c++;
    }//GEN-LAST:event_c1MousePressed

    private void c1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c1MouseDragged
        this.puntoMouse(c1,"c1");
    }//GEN-LAST:event_c1MouseDragged

    private void c5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c5MousePressed
        this.eventoMouse(evt);
        c++;
    }//GEN-LAST:event_c5MousePressed

    private void c5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c5MouseDragged
        this.puntoMouse(c5,"c5");
    }//GEN-LAST:event_c5MouseDragged

    private void c2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c2MousePressed
        this.eventoMouse(evt);
        c++;
    }//GEN-LAST:event_c2MousePressed

    private void c2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c2MouseDragged
        this.puntoMouse(c2,"c2");
    }//GEN-LAST:event_c2MouseDragged

    private void c6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c6MousePressed
        this.eventoMouse(evt);
        c++;
    }//GEN-LAST:event_c6MousePressed

    private void c6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c6MouseDragged
        this.puntoMouse(c6,"c6");
    }//GEN-LAST:event_c6MouseDragged

    private void c8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c8MousePressed
        this.eventoMouse(evt);
        c++;
    }//GEN-LAST:event_c8MousePressed

    private void c8MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c8MouseDragged
        this.puntoMouse(c8,"c8");
    }//GEN-LAST:event_c8MouseDragged

    private void c4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c4MousePressed
        this.eventoMouse(evt);
        c++;
    }//GEN-LAST:event_c4MousePressed

    private void c4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c4MouseDragged
        this.puntoMouse(c4,"c4");
    }//GEN-LAST:event_c4MouseDragged

    private void c7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c7MousePressed
        this.eventoMouse(evt);
        c++;
    }//GEN-LAST:event_c7MousePressed

    private void c3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c3MousePressed
        this.eventoMouse(evt);
        c++;
    }//GEN-LAST:event_c3MousePressed

    private void c3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c3MouseDragged
        this.puntoMouse(c3,"c3");
    }//GEN-LAST:event_c3MouseDragged

    private void c7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c7MouseDragged
        this.puntoMouse(c7,"c7");
    }//GEN-LAST:event_c7MouseDragged

    private void c9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c9MousePressed
        this.eventoMouse(evt);
        c++;
    }//GEN-LAST:event_c9MousePressed

    private void c9MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c9MouseDragged
        this.puntoMouse(c9,"c9");
    }//GEN-LAST:event_c9MouseDragged

    private void masActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masActionPerformed
        // TODO add your handling code here:
        
        c1.setVisible(true);
        c2.setVisible(true);
        c3.setVisible(true);
        c4.setVisible(true);
        c5.setVisible(true);
        c6.setVisible(true);
        c7.setVisible(true);
        c8.setVisible(true);
        c9.setVisible(true);
        
    }//GEN-LAST:event_masActionPerformed

    private void sanarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sanarActionPerformed
        // TODO add your handling code here:
        if(p!=true){
        panda.setIcon(pandaInicio);}
        v=true;
        p=true;
        si=0;
        
    }//GEN-LAST:event_sanarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(comedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(comedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(comedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(comedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new comedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel c1;
    private javax.swing.JLabel c2;
    private javax.swing.JLabel c3;
    private javax.swing.JLabel c4;
    private javax.swing.JLabel c5;
    private javax.swing.JLabel c6;
    private javax.swing.JLabel c7;
    private javax.swing.JLabel c8;
    private javax.swing.JLabel c9;
    private javax.swing.JButton cerrar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondocomida;
    private javax.swing.JButton mas;
    private javax.swing.JLabel panda;
    private javax.swing.JButton reiniciar;
    private javax.swing.JLabel roca;
    private javax.swing.JButton sanar;
    // End of variables declaration//GEN-END:variables
}
