/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asearpanda;
import javax.swing.ImageIcon;
/**
 *
 * @author Carmen Jimenez
 */
public class baño extends javax.swing.JFrame {
    ImageIcon imagen;
    ImageIcon imagen2;
    ImageIcon panda;
    ImageIcon jabon;
    int cont = 0;
    /**
     * Creates new form baño
     */
    public baño() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        burbujas = new javax.swing.JLabel();
        agua = new javax.swing.JLabel();
        panda_Banandose = new javax.swing.JLabel();
        tina = new javax.swing.JLabel();
        ducha = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();
        terminar = new javax.swing.JButton();
        agregarJabon = new javax.swing.JButton();
        iniciar = new javax.swing.JButton();
        PandaInicio = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusableWindowState(false);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(burbujas, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 200, 50));
        getContentPane().add(agua, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 160, 150));
        getContentPane().add(panda_Banandose, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 250, 150));

        tina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asearpanda/imagenes/tina.png"))); // NOI18N
        getContentPane().add(tina, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        ducha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asearpanda/imagenes/ducha_1.png"))); // NOI18N
        ducha.setBorder(null);
        ducha.setContentAreaFilled(false);
        ducha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duchaActionPerformed(evt);
            }
        });
        getContentPane().add(ducha, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asearpanda/imagenes/cerrar_icono_pequeño.png"))); // NOI18N
        cerrar.setToolTipText("Cerrar");
        cerrar.setBorder(null);
        cerrar.setContentAreaFilled(false);
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, -1, -1));

        terminar.setFont(new java.awt.Font("Shadows Into Light", 1, 14)); // NOI18N
        terminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asearpanda/imagenes/terminado.png"))); // NOI18N
        terminar.setText("Terminar");
        terminar.setToolTipText("Terminar");
        terminar.setBorder(null);
        terminar.setContentAreaFilled(false);
        terminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminarActionPerformed(evt);
            }
        });
        getContentPane().add(terminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        agregarJabon.setBackground(new java.awt.Color(255, 204, 204));
        agregarJabon.setFont(new java.awt.Font("Shadows Into Light", 0, 18)); // NOI18N
        agregarJabon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asearpanda/imagenes/naranja.jpg"))); // NOI18N
        agregarJabon.setText("Agregar jabón");
        agregarJabon.setBorder(null);
        agregarJabon.setContentAreaFilled(false);
        agregarJabon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agregarJabon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarJabonActionPerformed(evt);
            }
        });
        getContentPane().add(agregarJabon, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 140, 30));

        iniciar.setFont(new java.awt.Font("Shadows Into Light", 0, 18)); // NOI18N
        iniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asearpanda/imagenes/siguiente.png"))); // NOI18N
        iniciar.setText("Iniciar");
        iniciar.setBorder(null);
        iniciar.setContentAreaFilled(false);
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });
        getContentPane().add(iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 120, 50));

        PandaInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asearpanda/imagenes/1490550816_funny-panda-dancing.gif"))); // NOI18N
        getContentPane().add(PandaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 250, 260));

        jButton1.setFont(new java.awt.Font("Shadows Into Light", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asearpanda/imagenes/volver.png"))); // NOI18N
        jButton1.setText("Reiniciar");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jButton2.setFont(new java.awt.Font("Shadows Into Light", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asearpanda/imagenes/naranja.jpg"))); // NOI18N
        jButton2.setText("Llenar nuevamente");
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 140, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asearpanda/imagenes/fondi.png"))); // NOI18N
        fondo.setText("jLabel1");
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void duchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duchaActionPerformed
        // TODO add your handling code here:
        if (cont==0){
            imagen =new ImageIcon (getClass().getResource("/asearpanda/imagenes/gotas-01.gif"));  
            agua.setIcon(imagen);
            cont++;
        }
        else if (cont!=0){
            agua.setIcon(imagen2);
            cont=0;
    }
    }//GEN-LAST:event_duchaActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cerrarActionPerformed

    private void terminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminarActionPerformed
        // TODO add your handling code here:
        cdialog cd= new cdialog("Pandi esta limpio :)"); 
        cd.setVisible(true);
        dispose();
    }//GEN-LAST:event_terminarActionPerformed

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
        // TODO add your handling code here:
        panda =new ImageIcon (getClass().getResource("/asearpanda/imagenes/84.gif"));  
        panda_Banandose.setIcon(panda);
        PandaInicio.setIcon(imagen2);
    }//GEN-LAST:event_iniciarActionPerformed

    private void agregarJabonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarJabonActionPerformed
        // TODO add your handling code here:
        jabon =new ImageIcon (getClass().getResource("/asearpanda/imagenes/burbuja.gif"));  
        burbujas.setIcon(jabon);
    }//GEN-LAST:event_agregarJabonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        panda =new ImageIcon (getClass().getResource("/asearpanda/imagenes/1490550816_funny-panda-dancing.gif")); 
        PandaInicio.setIcon(panda);
        panda_Banandose.setIcon(imagen2);
        burbujas.setIcon(imagen2);
        agua.setIcon(imagen2);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        burbujas.setIcon(imagen2);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(baño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(baño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(baño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(baño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new baño().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PandaInicio;
    private javax.swing.JButton agregarJabon;
    private javax.swing.JLabel agua;
    private javax.swing.JLabel burbujas;
    private javax.swing.JButton cerrar;
    private javax.swing.JButton ducha;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton iniciar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel panda_Banandose;
    private javax.swing.JButton terminar;
    private javax.swing.JLabel tina;
    // End of variables declaration//GEN-END:variables
}
