/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pandi;
import minijuego_pandi.*;
import java.awt.MouseInfo;
import java.awt.Point;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
/**
 *
 * @author Carmen Jimenez
 */
public class rompecabezas extends javax.swing.JFrame {
    
    ImageIcon pc =new ImageIcon (getClass().getResource("/minijuego_pandi/partes/pandaCompleto.png"));
    ImageIcon ori =new ImageIcon (getClass().getResource("/minijuego_pandi/partes/orejaIzquierdaO.png"));
    ImageIcon ord =new ImageIcon (getClass().getResource("/minijuego_pandi/partes/orejaDerecha.png"));
    ImageIcon oji =new ImageIcon (getClass().getResource("/minijuego_pandi/partes/ojoIzquierdo.png"));
    ImageIcon ojd =new ImageIcon (getClass().getResource("/minijuego_pandi/partes/ojoDerecho.png"));
    ImageIcon caraImg =new ImageIcon (getClass().getResource("/minijuego_pandi/partes/cara.png"));
    ImageIcon bocaImg =new ImageIcon (getClass().getResource("/minijuego_pandi/partes/boca.png"));
    ImageIcon hombroImg =new ImageIcon (getClass().getResource("/minijuego_pandi/partes/HombrosO.png"));
    ImageIcon panzaImg =new ImageIcon (getClass().getResource("/minijuego_pandi/partes/panza.png"));
    ImageIcon brazoIImg =new ImageIcon (getClass().getResource("/minijuego_pandi/partes/brazoIzquierdo.png" ));
    ImageIcon brazoDimg =new ImageIcon (getClass().getResource("/minijuego_pandi/partes/BrazoDerecho.png"));
    ImageIcon pataIImg =new ImageIcon (getClass().getResource("/minijuego_pandi/partes/pataIzquierda.png"));
    ImageIcon pataDImg =new ImageIcon (getClass().getResource("/minijuego_pandi/partes/pataDerecha.png"));
    ImageIcon nada;
    
    cdialog cd = new cdialog("<html>!Muy bien!, has completado el\nrompecabezas");
    boolean r=false;
    int x,y;
    int fin=0;
    
    /**
     * Creates new form rompecabezas
     */
    public rompecabezas() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        reiniciar.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cerrar = new javax.swing.JButton();
        reiniciar = new javax.swing.JButton();
        info = new javax.swing.JButton();
        pandaC = new javax.swing.JLabel();
        orejaI = new javax.swing.JLabel();
        orejaD = new javax.swing.JLabel();
        ojoI = new javax.swing.JLabel();
        ojoD = new javax.swing.JLabel();
        boca = new javax.swing.JLabel();
        hombro = new javax.swing.JLabel();
        brazoI = new javax.swing.JLabel();
        brazoD = new javax.swing.JLabel();
        panza = new javax.swing.JLabel();
        pataI = new javax.swing.JLabel();
        pataD = new javax.swing.JLabel();
        cara = new javax.swing.JLabel();
        orejaI1 = new javax.swing.JLabel();
        orejaD1 = new javax.swing.JLabel();
        ojoI1 = new javax.swing.JLabel();
        ojoD1 = new javax.swing.JLabel();
        boca1 = new javax.swing.JLabel();
        hombro1 = new javax.swing.JLabel();
        brazoI1 = new javax.swing.JLabel();
        brazoD1 = new javax.swing.JLabel();
        panza1 = new javax.swing.JLabel();
        pataI1 = new javax.swing.JLabel();
        pataD1 = new javax.swing.JLabel();
        cara1 = new javax.swing.JLabel();
        marco = new javax.swing.JLabel();
        fondoR = new javax.swing.JLabel();
        fondoPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minijuego_pandi/imagenes/boton_cerrar.png"))); // NOI18N
        cerrar.setBorder(null);
        cerrar.setBorderPainted(false);
        cerrar.setContentAreaFilled(false);
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 20, -1, -1));

        reiniciar.setFont(new java.awt.Font("Shadows Into Light", 1, 18)); // NOI18N
        reiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minijuego_pandi/imagenes/reiniciar.png"))); // NOI18N
        reiniciar.setText("Reiniciar");
        reiniciar.setBorder(null);
        reiniciar.setBorderPainted(false);
        reiniciar.setContentAreaFilled(false);
        reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarActionPerformed(evt);
            }
        });
        getContentPane().add(reiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 170, -1, -1));

        info.setFont(new java.awt.Font("Shadows Into Light", 1, 18)); // NOI18N
        info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minijuego_pandi/imagenes/sabiasque.png"))); // NOI18N
        info.setText("Sabias que...");
        info.setBorder(null);
        info.setBorderPainted(false);
        info.setContentAreaFilled(false);
        info.setHideActionText(true);
        info.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        info.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        info.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoActionPerformed(evt);
            }
        });
        getContentPane().add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 140, 110, -1));
        getContentPane().add(pandaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 130, 460, 500));

        orejaI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minijuego_pandi/partes/orejaIzquierdaO.png"))); // NOI18N
        orejaI.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                orejaIMouseDragged(evt);
            }
        });
        orejaI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                orejaIMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                orejaIMouseReleased(evt);
            }
        });
        getContentPane().add(orejaI, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 440, 100, 110));

        orejaD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minijuego_pandi/partes/orejaDerecha.png"))); // NOI18N
        orejaD.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                orejaDMouseDragged(evt);
            }
        });
        orejaD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                orejaDMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                orejaDMouseReleased(evt);
            }
        });
        getContentPane().add(orejaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 340, 100, 110));

        ojoI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minijuego_pandi/partes/ojoIzquierdo.png"))); // NOI18N
        ojoI.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ojoIMouseDragged(evt);
            }
        });
        ojoI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ojoIMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ojoIMouseReleased(evt);
            }
        });
        getContentPane().add(ojoI, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 570, 90, 100));

        ojoD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minijuego_pandi/partes/ojoDerecho.png"))); // NOI18N
        ojoD.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ojoDMouseDragged(evt);
            }
        });
        ojoD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ojoDMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ojoDMouseReleased(evt);
            }
        });
        getContentPane().add(ojoD, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 550, -1, 100));

        boca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minijuego_pandi/partes/boca.png"))); // NOI18N
        boca.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bocaMouseDragged(evt);
            }
        });
        boca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bocaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bocaMouseReleased(evt);
            }
        });
        getContentPane().add(boca, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 390, -1, -1));

        hombro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minijuego_pandi/partes/HombrosO.png"))); // NOI18N
        hombro.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                hombroMouseDragged(evt);
            }
        });
        hombro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hombroMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                hombroMouseReleased(evt);
            }
        });
        getContentPane().add(hombro, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 510, -1, -1));

        brazoI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minijuego_pandi/partes/brazoIzquierdo.png"))); // NOI18N
        brazoI.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                brazoIMouseDragged(evt);
            }
        });
        brazoI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                brazoIMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                brazoIMouseReleased(evt);
            }
        });
        getContentPane().add(brazoI, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 570, 80, -1));

        brazoD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minijuego_pandi/partes/BrazoDerecho.png"))); // NOI18N
        brazoD.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                brazoDMouseDragged(evt);
            }
        });
        brazoD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                brazoDMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                brazoDMouseReleased(evt);
            }
        });
        getContentPane().add(brazoD, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 440, -1, -1));

        panza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minijuego_pandi/partes/panza.png"))); // NOI18N
        panza.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panzaMouseDragged(evt);
            }
        });
        panza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panzaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panzaMouseReleased(evt);
            }
        });
        getContentPane().add(panza, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 360, -1, 130));

        pataI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minijuego_pandi/partes/pataIzquierda.png"))); // NOI18N
        pataI.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pataIMouseDragged(evt);
            }
        });
        pataI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pataIMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pataIMouseReleased(evt);
            }
        });
        getContentPane().add(pataI, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 590, -1, -1));

        pataD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minijuego_pandi/partes/pataDerecha.png"))); // NOI18N
        pataD.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pataDMouseDragged(evt);
            }
        });
        pataD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pataDMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pataDMouseReleased(evt);
            }
        });
        getContentPane().add(pataD, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, -1, -1));

        cara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minijuego_pandi/partes/cara.png"))); // NOI18N
        cara.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cara.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                caraMouseDragged(evt);
            }
        });
        cara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                caraMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                caraMouseReleased(evt);
            }
        });
        getContentPane().add(cara, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, -1, -1));
        getContentPane().add(orejaI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 152, -1, 110));
        getContentPane().add(orejaD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 152, -1, 110));
        getContentPane().add(ojoI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 272, 100, 100));
        getContentPane().add(ojoD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 271, 90, 100));
        getContentPane().add(boca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 350, -1, -1));
        getContentPane().add(hombro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 405, 290, -1));
        getContentPane().add(brazoI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 393, 80, -1));
        getContentPane().add(brazoD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 392, 80, -1));
        getContentPane().add(panza1, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 452, 280, 130));
        getContentPane().add(pataI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 550, 120, -1));
        getContentPane().add(pataD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 549, 120, -1));

        cara1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(cara1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 142, 330, -1));

        marco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minijuego_pandi/partes/marcoPanda.png"))); // NOI18N
        getContentPane().add(marco, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 410, 500));

        fondoR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minijuego_pandi/imagenes/fondo_bambu.jpg"))); // NOI18N
        getContentPane().add(fondoR, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 510, 550));

        fondoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minijuego_pandi/imagenes/cielo2.jpg"))); // NOI18N
        getContentPane().add(fondoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cuadro(int n){
        fin+=n;
        
            if(fin==12){
            cd.setVisible(true);
            pandaC.setIcon(pc);
            reiniciar.setVisible(true);
            }
            if(r==true){
                reiniciar();
            }
        
    }
    
    public void reiniciar(){
        boca.setVisible(true);
        boca1.setIcon(nada);
        brazoD.setVisible(true);
        brazoD1.setIcon(nada);
        brazoI.setVisible(true);
        brazoI1.setIcon(nada);
        cara.setVisible(true);
        cara1.setIcon(nada);
        hombro.setVisible(true);
        hombro1.setIcon(nada);
        ojoD.setVisible(true);
        ojoD1.setIcon(nada);
        ojoI.setVisible(true);
        ojoI1.setIcon(nada);
        orejaD.setVisible(true);
        orejaD1.setIcon(nada);
        orejaI.setVisible(true);
        orejaI1.setIcon(nada);
        panza.setVisible(true);
        panza1.setIcon(nada);
        pataI.setVisible(true);
        pataI1.setIcon(nada);
        pataD.setVisible(true);
        pataD1.setIcon(nada);
        pandaC.setIcon(nada);
        this.fin=0;
        reiniciar.setVisible(false);
    }
    
    public void eventoMouse(java.awt.event.MouseEvent evt){
        x=evt.getX();
        y=evt.getY();
    }
    public void puntoMouse(JLabel label,String img){
        label.setVisible(true);
        
        Point point = MouseInfo.getPointerInfo().getLocation();
        System.out.println(point);
        label.setLocation(point.x-x,point.y-y);
    }
    
    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cerrarActionPerformed

    private void orejaIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orejaIMousePressed
        this.eventoMouse(evt);
    }//GEN-LAST:event_orejaIMousePressed

    private void orejaIMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orejaIMouseDragged
        this.puntoMouse(orejaI,"ori");
    }//GEN-LAST:event_orejaIMouseDragged

    private void orejaDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orejaDMousePressed
        this.eventoMouse(evt);
    }//GEN-LAST:event_orejaDMousePressed

    private void orejaDMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orejaDMouseDragged
        this.puntoMouse(orejaD,"ord");
    }//GEN-LAST:event_orejaDMouseDragged

    private void caraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caraMousePressed
        this.eventoMouse(evt);
    }//GEN-LAST:event_caraMousePressed

    private void caraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caraMouseDragged
        this.puntoMouse(cara,"cara");
    }//GEN-LAST:event_caraMouseDragged

    private void ojoIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ojoIMousePressed
        this.eventoMouse(evt);
    }//GEN-LAST:event_ojoIMousePressed

    private void ojoIMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ojoIMouseDragged
        this.puntoMouse(ojoI,"oji");
    }//GEN-LAST:event_ojoIMouseDragged

    private void ojoDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ojoDMousePressed
        this.eventoMouse(evt);
    }//GEN-LAST:event_ojoDMousePressed

    private void ojoDMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ojoDMouseDragged
        this.puntoMouse(ojoD,"ojd");
    }//GEN-LAST:event_ojoDMouseDragged

    private void bocaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bocaMousePressed
        this.eventoMouse(evt);
    }//GEN-LAST:event_bocaMousePressed

    private void bocaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bocaMouseDragged
        this.puntoMouse(boca,"boca");
    }//GEN-LAST:event_bocaMouseDragged

    private void hombroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hombroMousePressed
        this.eventoMouse(evt);
    }//GEN-LAST:event_hombroMousePressed

    private void hombroMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hombroMouseDragged
        this.puntoMouse(hombro,"hom");
    }//GEN-LAST:event_hombroMouseDragged

    private void brazoIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brazoIMousePressed
        this.eventoMouse(evt);
    }//GEN-LAST:event_brazoIMousePressed

    private void brazoIMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brazoIMouseDragged
        this.puntoMouse(brazoI,"bi");
    }//GEN-LAST:event_brazoIMouseDragged

    private void brazoDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brazoDMousePressed
        this.eventoMouse(evt);
    }//GEN-LAST:event_brazoDMousePressed

    private void brazoDMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brazoDMouseDragged
        this.puntoMouse(brazoD,"bd");
    }//GEN-LAST:event_brazoDMouseDragged

    private void panzaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panzaMousePressed
        this.eventoMouse(evt);
    }//GEN-LAST:event_panzaMousePressed

    private void panzaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panzaMouseDragged
        this.puntoMouse(panza,"panza");
    }//GEN-LAST:event_panzaMouseDragged

    private void pataIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pataIMousePressed
        this.eventoMouse(evt);
    }//GEN-LAST:event_pataIMousePressed

    private void pataIMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pataIMouseDragged
        this.puntoMouse(pataI,"pti");
    }//GEN-LAST:event_pataIMouseDragged

    private void pataDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pataDMousePressed
        this.eventoMouse(evt);
    }//GEN-LAST:event_pataDMousePressed

    private void pataDMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pataDMouseDragged
        this.puntoMouse(pataD,"ptd");
    }//GEN-LAST:event_pataDMouseDragged

    private void pataDMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pataDMouseReleased
        // TODO add your handling code here:
        System.out.println("pata drecha: "+pataD.getLocation());
        if((pataD.getX()>=363 && pataD.getX()<=377)&&(pataD.getY()>=543&&pataD.getY()<=557)){
            pataD.setVisible(false);
            pataD1.setIcon(pataDImg);
//            fin++;
        cuadro(1);
        }else{
           pataD.setLocation(710,370);
        }
        
    }//GEN-LAST:event_pataDMouseReleased

    private void pataIMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pataIMouseReleased
        // TODO add your handling code here:
        System.out.println("pata drecha: "+pataD.getLocation());
        if((pataI.getX()>=234 && pataI.getX()<=248)&&(pataI.getY()>=543&&pataI.getY()<=557)){
            pataI.setVisible(false);
            pataI1.setIcon(pataIImg);
//            fin++;
            cuadro(1);
        }else{
           pataI.setLocation(970, 590);}
        
    }//GEN-LAST:event_pataIMouseReleased

    private void orejaIMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orejaIMouseReleased
        // TODO add your handling code here:
        System.out.println("oreja i: "+orejaI.getLocation());
        
        if((orejaI.getX()>=164 && orejaI.getX()<=178)&&(orejaI.getY()>=144&&orejaI.getY()<=158)){
            orejaI.setVisible(false);
            orejaI1.setIcon(ori);
//            fin++;
            cuadro(1);
        }else{
            orejaI.setLocation(1250, 440);
        }
        
    }//GEN-LAST:event_orejaIMouseReleased

    private void orejaDMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orejaDMouseReleased
        System.out.println("oreja i: "+orejaD.getLocation());
        
        if((orejaD.getX()>=451 && orejaD.getX()<=471)&&(orejaD.getY()>=144&&orejaD.getY()<=158)){
            orejaD.setVisible(false);
            orejaD1.setIcon(ord);
//            fin++;
            cuadro(1);
        }else{
            orejaD.setLocation(1220, 340);
        }
        
    }//GEN-LAST:event_orejaDMouseReleased

    private void ojoIMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ojoIMouseReleased
        System.out.println("ojo i: "+ojoI.getLocation());
        
        if((ojoI.getX()>=241 && ojoI.getX()<=255)&&(ojoI.getY()>=264&&ojoI.getY()<=279)){
            ojoI.setVisible(false);
            ojoI1.setIcon(oji);
//            fin++;
            cuadro(1);
        }else{
            ojoI.setLocation(1230, 570);
        }
        
    }//GEN-LAST:event_ojoIMouseReleased

    private void ojoDMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ojoDMouseReleased
        System.out.println("ojo d: "+ojoD.getLocation());
        
        if((ojoD.getX()>=379 && ojoD.getX()<=393)&&(ojoD.getY()>=265&&ojoD.getY()<=278)){
            ojoD.setVisible(false);
            ojoD1.setIcon(ojd);
//            fin++;
            cuadro(1);
        }else{
            ojoD.setLocation(1080, 550);
        }
        
    }//GEN-LAST:event_ojoDMouseReleased

    private void bocaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bocaMouseReleased
        System.out.println("boca: "+boca.getLocation());
        
        if((boca.getX()>=310 && boca.getX()<=324)&&(boca.getY()>=345&&boca.getY()<=359)){
            boca.setVisible(false);
            boca1.setIcon(bocaImg);
//            fin++;
            cuadro(1);
        }else{
            boca.setLocation(860, 390);
        }
        
    }//GEN-LAST:event_bocaMouseReleased

    private void hombroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hombroMouseReleased
        System.out.println("hombro: "+hombro.getLocation());
        
        if((hombro.getX()>=210 && hombro.getX()<=224)&&(hombro.getY()>=399&&hombro.getY()<=413)){
            hombro.setVisible(false);
            hombro1.setIcon(hombroImg);
//            fin++;
            cuadro(1);
        }else{
            hombro.setLocation(980, 510);
        }
        
    }//GEN-LAST:event_hombroMouseReleased

    private void brazoIMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brazoIMouseReleased
        System.out.println("Brazo i: "+brazoI.getLocation());
        
        if((brazoI.getX()>=174 && brazoI.getX()<=188)&&(brazoI.getY()>=387&&brazoI.getY()<=401)){
            brazoI.setVisible(false);
            brazoI1.setIcon(brazoIImg);
//            fin++;
            cuadro(1);
        }else{
           brazoI.setLocation(1160,570);
        }
        
    }//GEN-LAST:event_brazoIMouseReleased

    private void brazoDMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brazoDMouseReleased
        // TODO add your handling code here:
        System.out.println("Brazo d: "+brazoD.getLocation());
        
        if((brazoD.getX()>=460 && brazoD.getX()<=484)&&(brazoD.getY()>=386&&brazoD.getY()<=400)){
            brazoD.setVisible(false);
            brazoD1.setIcon(brazoDimg);
//            fin++;
            cuadro(1);
        }else{
            brazoD.setLocation(940, 440);
        }
        
    }//GEN-LAST:event_brazoDMouseReleased

    private void panzaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panzaMouseReleased
        System.out.println("panza: "+panza.getLocation());
        
        if((panza.getX()>=220 && panza.getX()<=234)&&(panza.getY()>=445&&panza.getY()<=459)){
            panza.setVisible(false);
            panza1.setIcon(panzaImg);
//            fin++;
            cuadro(1);
        }else{
            panza.setLocation(970, 360);
        }
    }//GEN-LAST:event_panzaMouseReleased

    private void caraMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caraMouseReleased
        System.out.println("cara: "+cara.getLocation());
        
        if((cara.getX()>=193 && cara.getX()<=207)&&(cara.getY()>=136 && cara.getY()<=150)){
            cara.setVisible(false);
            cara1.setIcon(caraImg);
//            fin++;
            cuadro(1);
        }else{
            cara.setLocation(650, 440);
        }
    }//GEN-LAST:event_caraMouseReleased

    private void reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciarActionPerformed
        reiniciar();
    }//GEN-LAST:event_reiniciarActionPerformed

    private void infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoActionPerformed
        // TODO add your handling code here:
        sabiasque sq = new sabiasque("<html>¿El panda tiene seis dedos?\n" +
"\n" +
"A primera vista parecen tener un sexto dedo en sus palmas,\n" +
"pero análisis anatómicos nos muestran que no se trata de \n" +
"un dedo realmente es la modificación de un hueso conocido\n" +
"como sesamoideo radial, las cuales les son de granutilidad\n" +
" a la hora de rascar/cortar el bambú para comérselo.");
        sq.setVisible(true);
    }//GEN-LAST:event_infoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rompecabezas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rompecabezas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rompecabezas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rompecabezas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rompecabezas().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel boca;
    private javax.swing.JLabel boca1;
    private javax.swing.JLabel brazoD;
    private javax.swing.JLabel brazoD1;
    private javax.swing.JLabel brazoI;
    private javax.swing.JLabel brazoI1;
    private javax.swing.JLabel cara;
    private javax.swing.JLabel cara1;
    private javax.swing.JButton cerrar;
    private javax.swing.JLabel fondoPrincipal;
    private javax.swing.JLabel fondoR;
    private javax.swing.JLabel hombro;
    private javax.swing.JLabel hombro1;
    private javax.swing.JButton info;
    private javax.swing.JLabel marco;
    private javax.swing.JLabel ojoD;
    private javax.swing.JLabel ojoD1;
    private javax.swing.JLabel ojoI;
    private javax.swing.JLabel ojoI1;
    private javax.swing.JLabel orejaD;
    private javax.swing.JLabel orejaD1;
    private javax.swing.JLabel orejaI;
    private javax.swing.JLabel orejaI1;
    private javax.swing.JLabel pandaC;
    private javax.swing.JLabel panza;
    private javax.swing.JLabel panza1;
    private javax.swing.JLabel pataD;
    private javax.swing.JLabel pataD1;
    private javax.swing.JLabel pataI;
    private javax.swing.JLabel pataI1;
    private javax.swing.JButton reiniciar;
    // End of variables declaration//GEN-END:variables
}
